---
- name: Install mcp-rag-server
  hosts: all
  become: no
  vars:
    user_home: "{{ ansible_env.HOME }}"
    uv_path: "{{ user_home }}/.cargo/bin/uv"
    venv_dir: "{{ user_home }}/.venvs/mcp-rag-server"

  tasks:
    - name: Create a virtual environment for mcp-rag-server
      ansible.builtin.shell:
        cmd: "{{ uv_path }} venv {{ venv_dir }}"
        creates: "{{ venv_dir }}/bin/activate"

    - name: Install mcp-rag-server from GitHub develop branch
      ansible.builtin.shell:
        cmd: "{{ venv_dir }}/bin/uv pip install git+https://github.com/TatsuyaKatayama/mcp-rag-server.git@develop"
